### PR TITLE
Adding defaultHeader method

### LINKED ISSUE #3: Support for default headers
As just as the defaultContentType method, there should be a defaultHeader("name", "value") to add default headers in the response

### PR DESCRIPTION
**Pull request by gabteles**
Hi! This PR allows to set default headers to every response. 

closes #3

### CODE REVIEW

**Comment by gabfssilva** [comment]
Nice work, @gabteles! Do you think you can also implement this in the Scala module?

**Comment by gabteles** [comment]
@gabfssilva I'll try to!

**Comment by gabfssilva** [comment]
Nice! I guess you should change three things:

1) Use the implicit asScala/asJava instead of other methods, it is easier. Instead of:

```scala
mapAsJavaMap(map)
```

Do:

```scala
map.asJava
```

You just need to use this import:
```scala
import scala.collections.JavaConverters._
```

2) Since defaultHeaders is a global variable, you don't need to pass it into **handle** method.

Instead of:

```scala
def handle(path: String, produces: String, method: String, matcher: Function[ScalaDslRequest, Boolean], handler: Function[ScalaDslRequest, Future[_ >: Any]], defaultHeaders: Map[String, String])(implicit ec: ExecutionContext): Unit
```
You could go back to

```scala
+  def handle(path: String, produces: String, method: String, matcher: Function[ScalaDslRequest, Boolean], handler: Function[ScalaDslRequest, Future[_ >: Any]])(implicit ec: ExecutionContext): Unit
```

And use the global variable inside the method:

```scala
(...)
addHandler(new RequestHandler(method, path, produces, javaFunc, javaMatcher, defaultHeaders.asJava))
```

**You should do the same in Java version (org.geryon.Http)**

3) Also, de defaultHeader method should receive a Tuple[String, String] instead of two parameters:

```scala
def defaultHeader(header: (String, String)): Unit = {
  val (name, value) = header
  HttpServerHandler.defaultHeaders(name) = value
}
```

If you want to set a defaultHeader:

```scala
defaultHeader("X-Powered-By" -> "Geryon")
```

I guess after that it'd be okay to merge. Thanks again! ;)

**Comment by gabteles** [comment]
@gabfssilva, i've fixed the issues you pointed, thanks for the code review. 
I also did some refact of the generation of responses in RequestDispatcher, to improve legibility a bit.

**Comment by gabfssilva** [comment]
Merged, thanks!

**Pull request merged**
